name: Dev Workflows
on:
  push:
    branches:
    - main
jobs:
  dev-job-first:
    name: dev-job-first
    runs-on: ubuntu-latest
    steps:
    - name: Crate a dev.txt
      run: echo "dev file" > dev.txt
    - uses: actions/upload-artifact@v4
      with:
        name: dev-artifact
        path: ./dev.txt

  dev-job-second:
    name: dev-job-second
    runs-on: ubuntu-latest
    needs: dev-job-first
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dev-artifact
    - name: Show dev.txt
      run:  cat dev.txt
